version: "3"
services:
  app:
    container_name: autodeploy
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT}:3010"
    volumes:
      - .:/autodeploy
      - /autodeploy/node_modules
    links:
      - mongo
  mongo:
    container_name: autodeploy-mongo
    restart: always
    image: mongo:5
